# Generated by Django 5.1 on 2024-11-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=1)),
                ('email', models.TextField(max_length=500)),
                ('bio', models.TextField(default='TBA', max_length=2000)),
            ],
        ),
    ]
