# Generated by Django 5.1 on 2024-11-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('Contacts', 'Contact')
    ]
