# Generated by Django 5.1 on 2024-11-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_delete_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='job',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='nationality',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
