# Generated by Django 5.1 on 2024-11-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_first_name_contact_job_contact_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
