# Generated by Django 5.1 on 2024-11-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='', max_length=200)),
                ('password', models.TextField(default='', max_length=200)),
                ('first_name', models.TextField(default='', max_length=200)),
                ('last_name', models.TextField(default='', max_length=200)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('nationality', models.TextField(default='', max_length=200)),
                ('email', models.TextField(default='', max_length=500)),
                ('birthday', models.DateField(null=True)),
            ],
        ),
    ]
